# Generated by Django 4.2 on 2023-04-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.FloatField(verbose_name='whole area of storage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_closed',
            field=models.DateField(blank=True, null=True, verbose_name='date of closing the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_opened',
            field=models.DateField(blank=True, null=True, verbose_name='date of opening the order'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='area',
            field=models.FloatField(verbose_name='whole area of storage'),
        ),
    ]
