# Generated by Django 4.2 on 2023-04-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0002_alter_order_area_alter_order_date_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_expired',
            field=models.BooleanField(blank=True, null=True, verbose_name='area was cleared'),
        ),
    ]
