# Generated by Django 4.2 on 2023-04-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0004_owner_client_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='uniq chat_id for Bot'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='uniq chat_id for Bot'),
        ),
    ]
