# Generated by Django 4.2 on 2023-04-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0005_alter_client_chat_id_alter_owner_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='chat_id for Bot'),
        ),
    ]
