# Generated by Django 4.2 on 2023-04-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0006_alter_client_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='telegram account for communication'),
        ),
    ]
