# Generated by Django 4.2 on 2023-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0007_client_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_chat_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='e-mail address'),
        ),
    ]
