# Generated by Django 4.2 on 2023-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0008_remove_order_client_chat_id_alter_client_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metr_1_3', models.FloatField(verbose_name='cost  0 <= sq < 3')),
                ('metr_3_7', models.FloatField(verbose_name='cost 3 <= sq < 7')),
                ('metr_7_10', models.FloatField(verbose_name='cost 7 <= sq < 10')),
                ('metr_10', models.FloatField(verbose_name='cost sq>= 10')),
                ('mass_0_10', models.FloatField(verbose_name='cost 0 <= m < 10')),
                ('mass_10_25', models.FloatField(verbose_name='cost 10 <= m < 25')),
                ('mass_25_40', models.FloatField(verbose_name='cost 25 <= m < 40')),
                ('mass_40_70', models.FloatField(verbose_name='cost 40 <= m < 70')),
                ('mass_70_100', models.FloatField(verbose_name='cost 70 <= m < 100')),
                ('mass_100', models.FloatField(verbose_name='cost m >= 100')),
            ],
        ),
    ]
