# Generated by Django 4.2 on 2023-04-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0009_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='metr_1_3',
            new_name='metr_0_3',
        ),
    ]
