# Generated by Django 4.2 on 2023-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0010_rename_metr_1_3_cost_metr_0_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='storage',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='cost of order'),
        ),
        migrations.AddField(
            model_name='order',
            name='mass',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='range of mass for rents'),
        ),
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='range of area for rents'),
        ),
    ]
