# Generated by Django 4.2 on 2023-04-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0011_remove_order_storage_order_amount_order_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='admin_warehouse.client', verbose_name='client'),
        ),
    ]
