# Generated by Django 4.2 on 2023-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warehouse', '0012_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tg_account',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='telegram account for communication'),
        ),
    ]
